//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondourApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlotDetail()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int PlotNumber { get; set; }
        public string Area { get; set; }
        public Nullable<int> DocumentNumber { get; set; }
        public Nullable<int> YearOfRegistration { get; set; }
        public string RegistrationOffice { get; set; }
        public string PlotDocumentPhoto { get; set; }
        public string Nominee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
