//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondourApp.Models.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentStatu
    {
        public int EmpStatusId { get; set; }
        public string EmpStatus { get; set; }
    }
}
